name: flutter_ble
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^1.32.12
  permission_handler: ^11.3.1
  get: ^4.3.8
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  firebase_core: ^3.4.1
  firebase_database: ^11.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/logo.png